language: node_js
node_js:
  - "node"
before_deploy:
  - touch dist/README.md
  - cp README.md dist/README.md
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  target-branch: master
  fqdn: kevinmarley.ca
  on:
    branch: dev
